variable "pm_user" {}
variable "pm_password" {}
variable "pm_api_url" {}
variable "container_pass" {}
variable "target_node" {}
variable "ostemplate" {}
variable "tags" {}
variable "nameserver" {}
variable "hostname" {}