resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: latest

resources:
- name: repo
  type: git
  source:
    uri: https://github.com/chad2448/terraform.git
    branch: main

- name: terraform
  type: terraform
  source:
    backend_type: local
    # backend_config:
    #   path: ../../../proxmox/terraform.tfstate
    vars:
      pm_api_url: {{pm_api_url}}
      pm_user: {{pm_user}}
      pm_password: {{pm_password}}
      container_pass: {{container_pass}}
      target_node: {{target_node}}
      ostemplate: {{ostemplate}}
      tags: {{tags}}
      nameserver: {{nameserver}}
      hostname: {{hostname}}
  
jobs:
- name: update-infrastructure
  plan:
  - get: repo
  - put: terraform
    params:
      # env_name: e2e
      terraform_source: terraform/proxmox
  - task: show-outputs
    config:
      platform: linux
      inputs:
        - name: terraform
      run:
        path: /bin/sh
        args:
          - -c
          - |
              echo "name: $(cat terraform/name)"
              echo "metadata: $(cat terraform/metadata)"


# jobs:
# - name: terraform-plan
#   plan:
#   - get: repo
#     trigger: false
#   - put: terraform
#     params:
#       terraform_source: terraform/proxmox
#       plan_only: true

# - name: terraform-apply
#   plan:
#   - get: repo
#     trigger: false
#     passed: [terraform-plan]
#   - get: terraform
#     trigger: false
#     passed: [terraform-plan]
#   - put: terraform
#     params:
#       terraform_source: terraform/proxmox
#       plan_run: false