variable "username" {}
variable "password" {}
variable "target" {}
variable "team" {}
variable "url" {}
variable "git-team-name" {}
variable "git-org-name" {}
variable "git-username" {}
variable "new-team-name" {}
variable "new-pipeline-name" {}
variable "pipeline-config-1" {}
variable "repository" {}
variable "pm_api_url" {}
variable "pm_user" {}
variable "pm_password" {}
variable "container_pass" {}
variable "target_node" {}
variable "ostemplate" {}
variable "tags" {}
variable "nameserver" {}
variable "hostname" {}
variable "environment_access_key" {}
variable "environment_secret_key" {}